ERLC = erlc
ERl = erl
SRC = buscar.erl
SRC1 = buscar
BEAM = buscar.beam

compile:
	$(ERLC) $(SRC)

run: $(BEAM)
	erl -noshell -s $(SRC1) main -s init stop

all:	compile		run

clean:
	rm -f *.beam