ERLC = erlc
ERl = erl
SRC = fibonacci.erl
SRC1 = fibonacci
BEAM = fibonacci.beam

compile:
	$(ERLC) $(SRC)

run: $(BEAM)
	erl -noshell -s $(SRC1) main -s init stop

all:	compile		run

clean:
	rm -f *.beam